spring.application.name=GestionProduits
server.port=8090
#Configuration de la base de données H2
#spring.datasource.url=jdbc:h2:mem:product-db
#spring.h2.console.enabled=true
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Configuration de la base de donnees MySQL
# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cs2c?useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Root@2026
#Configuration JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true